apply plugin: 'com.android.application'

android {
    defaultConfig {
        compileSdk Integer.parseInt(project.ANDROID_BUILD_SDK_VERSION)
        applicationId 'com.tom_roush.pdfbox.sample'
        minSdkVersion 27
        targetSdkVersion Integer.parseInt(project.ANDROID_BUILD_TARGET_SDK_VERSION)
        versionName project.VERSION_NAME
        versionCode Integer.parseInt(project.VERSION_CODE)
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }


    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
    lint {
        abortOnError false
    }
    namespace 'com.tom_roush.pdfbox.sample'
}

dependencies {
    implementation project(':library')
//    implementation "com.tom-roush:pdfbox-android:${project.VERSION_NAME}"
    implementation 'androidx.appcompat:appcompat:1.2.0'

    // Optional dependencies

    // Read JPX images
    implementation 'com.gemalto.jp2:jp2-android:1.0.3'
}
